export const machines = [
    {
        id: 'tz1993',
        name: 'Twilight Zone',
        manufacturer: 'Bally Midway',
        year: '1993',
        image: '../assets/tz1993.jpg',
        type: 'Solid State Electronic',
        description: 'Flippers (4), Pop bumpers (3), Ramps (2), Dual left inlanes, "Rocket" kicker.',
        price: 250,
    },
    {
        id: 'fb1972',
        name: 'Fireball',
        manufacturer: 'Bally',
        year: '1972',
        image: '../assets/fb1972.jpg',
        type: 'Electro-mechanical',
        description: '	Zipper flippers (2), Pop bumpers (3), Mushroom bumpers (3), Slingshots (2), Captive ball kick-out holes (2)',
        price: 150,
    },
    {
        id: 'ww1993',
        name: 'White Water ',
        manufacturer: '	Williams Electronics',
        year: '1993',
        image: '../assets/ww1993.jpg',
        type: 'Solid State Electronic',
        description: `Flippers (3), Pop bumpers (3), Upper mini-playfield, Left outlane kickback. Multiple ramps. "Whirlpool" funnel.`,
        price: 250,
    },
    {
        id: 'sl1965',
        name: 'Sky Line',
        manufacturer: 'Gottleib',
        year: '1965',
        image: '../assets/sl1965.jpg',
        type: 'Electro-mechanical',
        description: `Flippers (2), Pop bumpers (5), Slingshots (2), Standup targets (2), Multi-bumper, Dual outlanes.`,
        price: 100,
    },
    {
        id: 'taf1992',
        name: 'The Addams Family',
        manufacturer: 'Midway',
        year: '1992',
        image: '../assets/taf1992.jpg',
        type: 'Solid State Electronic',
        description: `	Flippers (4; 3 regular-sized, 1 "Thing Flips" game-controlled mini-flipper), Pop bumpers (5), Ramps (2), Kick-out holes (2), Dual left inlanes.`,
        price: 300,
    },
    {
        id: 'jp2019',
        name: 'Jurassic Park',
        manufacturer: 'Stern',
        year: '2019',
        image: '../assets/jp2019.jpg',
        type: 'Solid State Electronic',
        description: `	Flippers (3), Pop bumpers (3), Slingshots (2), Up-posts (4), Spinning target (1), Horizontal spinner. Newton ball post. 3 to 6-ball multiball.`,
        price: 350,
    },
    {
        id: 'gg1979',
        name: 'Gorgar',
        manufacturer: 'Williams',
        year: '1979',
        image: '../assets/gg1979.jpg',
        type: 'Solid State Electronic',
        description: `Flippers (2), Pop bumpers (3), Slingshots (2), Standup targets (4), 3-bank drop targets (2), Kick-out hole (1), Spinning target (1).`,
        price: 175,
    },
    {
        id: 'bh1981',
        name: 'Black Hole',
        manufacturer: 'Gottleib',
        year: '1981',
        image: '../assets/bh1981.jpg',
        type: 'Solid State Electronic',
        description: `	Flippers (6), Pop bumpers (6), Slingshots (3), 5-bank drop targets (1), 4-bank drop targets (2), 3-bank drop targets (1), Kick-out holes (2), Kick target (1), Horseshoe lane (1), Spinning target (1), Rollunder (1), Cellar hole (1), Right outlane ball detour gate.`,
        price: 200,
    },
    {
        id: 'sw1980',
        name: 'Seawitch',
        manufacturer: 'Stern',
        year: '1980',
        image: '../assets/sw1980.jpg',
        type: 'Solid State Electronic',
        description: `Flippers (4), Pop bumpers (3), Slingshots (2), Standup targets (4), 4-bank drop targets (2), 3-bank drop targets (1), Star Rollovers (2), Spinning target (1).`,
        price: '250',
    },
    {
        id:  'bg1980',
        name: 'Big Game',
        manufacturer: 'Stern',
        year: '1980',
        image: '../assets/bg1980.jpg',
        type: 'Solid State Electronic',
        description: `Flippers (4), Pop bumpers (3), Slingshots (2), Star rollovers (5), 3-bank drop targets (3), Spinning targets (2), Standup targets (2), Kick-out hole (1).`,
        price: '200',
    },
    {
        id:  'br1988',
        name: 'Banzai Run',
        manufacturer: 'Williams',
        year: '1988',
        image: '../assets/br1988.jpg',
        type: 'Solid State Electronic',
        description: `Flippers (3 horizontal, 3 vertical), Pop bumpers (3), Ramp (1), Kick-out hole (1), Spinning targets (2), Left outlane kickback, Captive balls (1 horizontal, 2 vertical), Up-post (between bottom flippers on the vertical playfield), Ball kicker next to the left slingshot, 2-ball Multiball.`,
        price: '300',
    },
    {
        id:  'at1975',
        name: 'Atlantis',
        manufacturer: 'Gottleib',   
        year: '1975',
        image: '../assets/at1975.jpg',
        type: 'Electro-mechanical',
        description: `Flippers (2), Pop bumpers (2), Slingshots (2), 10-bank drop targets (1), Right playfield has two parallel lanes of serial rollovers.`,
        price: '150',
    }
];